package no.nav.foreldrepenger.fpformidling.typer;

public enum RevurderingÅrsak {
    BARN_IKKE_REGISTRERT_FOLKEREGISTER,
    ARBEIDS_I_STØNADSPERIODEN,
    BEREGNINGSGRUNNLAG_UNDER_HALV_G,
    BRUKER_REGISTRERT_UTVANDRET,
    ARBEID_I_UTLANDET,
    IKKE_LOVLIG_OPPHOLD,
    OPPTJENING_IKKE_OPPFYLT,
    MOR_AKTIVITET_IKKE_OPPFYLT,
    ANNET,
}
