# Jetty
server.port=8080
context.path=/fpformidling
application.name=fpformidling

# Auditlogger
auditlogger.enabled=true
auditlogger.vendor=Foreldrepenger
auditlogger.product=fpformidling

## Klienter
# Verdikjede
dokgen.rest.base.url=http://fpdokgen.teamforeldrepenger

# PDL
pdl.base.url=http://pdl-api.pdl/graphql
pdl.tema=FOR
