## Klienter
# Eksterne (lokal)
pdl.base.url=https://pdl-api.dev-fss-pub.nais.io/graphql
pdl.scopes=api://dev-fss.pdl.pdl-api/.default

dokdist.rest.base.url=https://dokdistfordeling.dev-fss-pub.nais.io/rest/v1
dokdist.scopes=api://dev-fss.teamdokumenthandtering.dokdistfordeling/.default

journalpost.rest.v1.url=https://dokarkiv-q2.dev-fss-pub.nais.io/rest/journalpostapi/v1/journalpost
journalpost.scopes=api://dev-fss.teamdokumenthandtering.dokarkiv/.default

# Eksterne (felles)
organisasjon.rs.url=https://ereg-services.dev-fss-pub.nais.io/api/v2/organisasjon

# Oppgave
oppgave.rs.uri=https://oppgave.dev-fss-pub.nais.io/api/v1/oppgaver
oppgave.scopes=api://dev-fss.oppgavehandtering.oppgave/.default
