## Klienter
# Eksterne (lokal)
pdl.base.url=https://pdl-api.dev-fss-pub.nais.io/graphql
pdl.scopes=api://dev-fss.pdl.pdl-api/.default

dokdist.rest.base.url=https://dokdistfordeling.intern.dev.nav.no/rest/v1
dokdist.scopes=api://dev-fss.teamdokumenthandtering.dokdistfordeling/.default

journalpost.rest.v1.url=https://dokarkiv.intern.dev.nav.no/rest/journalpostapi/v1/journalpost
journalpost.scopes=api://dev-fss.teamdokumenthandtering.dokarkiv/.default

# Eksterne (felles)
organisasjon.rs.url=https://ereg-services.intern.dev.nav.no/api/v2/organisasjon

# Oppgave
oppgave.rs.uri=https://oppgave.intern.dev.nav.no/api/v1/oppgaver
oppgave.scopes=api://dev-fss.oppgavehandtering.oppgave/.default
