= Dokprod integrasjon

== Hensikt
Dokumentproduksjon er NAVs interne tjeneste for produsering av dokumenter for vilkårlige fagsystemer. Tjenesten tilbyr funksjonalitet rundt dokumentproduksjon slik at brukeren skal kunne produsere dokument basert på bestillingsinformasjon og brevdata fagsystemet har gitt. Når vedtaksløsningen trenger å sende eller forhåndsvise brev benyttes denne tjenesten.

== Hvordan

=== Produksjon av dokument
Brev produseres ved hjelp av tjenesten ProduserIkkeRedigerbartDokument i Dokumentproduksjon_v2. Hvem som skal motta brev spesifiseres av DOKUMENT_MOTTAKER-tabellen. Dette kan være søker og/eller verge. Requesten til ProduserIkkeRedigerbartDokument tar to felt: Dokumentbestillingsinformasjon og Brevdata (xml). Begge disse mappes opp basert på innhold i DOKUMENT_DATA- og DOKUMENT_FELLES-tabellene. DOKUMENT_DATA inneholder informasjon om hvilken behandling brevet gjelder, hvilken brevmal som skal brukes, tidspunkt for når dokumentet ble bestilt, og når det ble produsert. I DOKUMENT_FELLES finner vi informasjon som er relevant for hver enkelt dokumentmottaker.

=== Forhåndsvisning av dokument
Tjenesten ProduserDokumentUtkast i Dokumentproduksjon_v2 brukes til å forhåndsvise brev. Denne tjenesten tar to parametere: dokumenttypeId (hvilken dokumentmal som skal brukes) og brevdata (xml). Brevdata mappes opp som for produksjon av dokument.

=== Lagring
All informasjonen som sendes inn til dokprod-tjenestene finner vi i DOKUMENT_DATA- og DOKUMENT_FELLES-tabellene. Når vi mottar responsen fra dokprod settes DOKUMENT_ID og JOURNALPOST_ID i DOKUMENT_FELLES-tabellen.

=== Dokumentbestiller - hvordan legge til ny dokumentmal
Beskriver hva som må gjøres i Dokumentbestilleren for å kunne ta i bruk en ny dokumenttype (dokumentmal) for forhåndsvisning og produksjon av dokument (brev).

Utgangspunktet er at det foreligger en ny dokumenttype, i form av et XML-skjema fra DokProd. Anta at skjemaet har navn 0000xx.xsd.

. Ta inn skjema i dokumentbestiller-xsd
* Importere xsd til mappen xsd, navn foreldrepenger_0000xx.xsd
* Oppdatere pom for bygging
* Bygg
. Oppdater dokumentbestiller-api
* Implementere DokumentType med flettefelter, etter mønster av tidligere implementasjoner.
* Enkle dokumenttyper kan benytte implementasjonen StandardDokument uten endring.
. Oppdatere dokumentbestiller-impl
* Implementere DokumentTypeMapper:
** Håndtere flettefelter i mapFagType() etter mønster av tidligere implementasjoner
* Legg til mapperen med riktig malnavn i DokumentTypeRuter
. Verifikasjon og test
* Opprette/lagre dokumentdata:
** Kall lagreDokumentData() (i interface DokumentDataTjeneste)
* Generere dokument for forhåndsvisning:
** Kall forhandsvisDokument() (i interface DokumentBestillerApplikasjonTjeneste)
* Produsere dokument (sende):
** Kall produserDokument() (i interface DokumentBestillerApplikasjonTjeneste)

=== Annet
Lenke til dokumentasjon av tjeneste
https://confluence.adeo.no/pages/viewpage.action?pageId=205634878[tjeneste_v3:virksomhet:Dokumentproduksjon_v2 (2018-HL0)]
