package no.nav.foreldrepenger.fpformidling.opptjening;

public enum OpptjeningAktivitetType {
    AAP,
    ARBEID,
    DAGPENGER,
    FORELDREPENGER,
    FRILANS,
    MILITÆR_ELLER_SIVILTJENESTE,
    NÆRING,
    OMSORGSPENGER,
    OPPLÆRINGSPENGER(),
    PLEIEPENGER,
    FRISINN,
    ETTERLØNN_SLUTTPAKKE,
    SVANGERSKAPSPENGER,
    SYKEPENGER,
    VENTELØNN_VARTPENGER,
    VIDERE_ETTERUTDANNING,
    UTENLANDSK_ARBEIDSFORHOLD,
    UTDANNINGSPERMISJON
}
