kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: fpformidling
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
  image: {{image}}
  port: 8080
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  liveness:
    path: /fpformidling/internal/health/isAlive
    initialDelay: 30
    periodSeconds: 10
    failureThreshold: 27
    timeout: 5
  readiness:
    path: /fpformidling/internal/health/isReady
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
  preStopHookPath: /fpformidling/internal/health/preStop
  prometheus:
    enabled: true
    path: /fpformidling/internal/metrics/prometheus
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 80
  resources:
    limits:
      cpu: "2000m"
      memory: "2048Mi"
    requests:
      cpu: "100m"
      memory: "1024Mi"
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/systembruker
        kvPath: {{serviceuserkv}}
      - mountPath: /var/run/secrets/nais.io/appdynamics
        kvPath: /apikey/appdynamics/{{environment}}
  secureLogs:
    enabled: true
  env:
  {{#each env}}
   - name: {{@key}}
     value: "{{this}}"
  {{/each}}
