kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: fpformidling
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
  image: {{image}}
  port: 8080
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  liveness:
    path: /fpformidling/internal/health/isAlive
    initialDelay: 10
    periodSeconds: 10
    failureThreshold: 20
    timeout: 3
  readiness:
    path: /fpformidling/internal/health/isReady
    initialDelay: 10
    periodSeconds: 10
    failureThreshold: 20
    timeout: 3
  preStopHook:
    http:
      path: /fpformidling/internal/health/preStop
  prometheus:
    enabled: true
    path: /fpformidling/internal/metrics/prometheus
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    scalingStrategy:
      cpu:
        thresholdPercentage: 80
  resources:
    limits:
      memory: "{{limits.mem}}"
    requests:
      cpu: "{{requests.cpu}}"
      memory: "{{requests.mem}}"
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  gcp:
    sqlInstances:
      - type: {{db.dbVersion}}
        databases:
          - name: fpformidling
            envVarPrefix: DB
        tier: {{db.dbTier}}
        diskAutoresize: {{db.dbDiskAutoresize}}
        highAvailability: {{db.dbHighAvailability}}
        pointInTimeRecovery: {{db.dbPointInTimeRecovery}}
        collation: nb_NO.UTF8
        retainedBackups: {{db.dbRetainedBackups}}
        autoBackupHour: 2
        maintenance:
          day: 1
          hour: 4
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
        groups:
          {{#each groups as |group|}}
          - id: "{{group.uuid}}"
          {{/each}}
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
        - application: fpdokgen
          namespace: teamforeldrepenger
      external:
        - host: pdl-api.{{environment}}-fss-pub.nais.io
        - host: dokdistfordeling.{{environment}}-fss-pub.nais.io
        - host: dokarkiv.{{environment}}-fss-pub.nais.io
        - host: oppgave.{{environment}}-fss-pub.nais.io
        - host: ereg-services.{{environment}}-fss-pub.nais.io
        - host: fpsak-api.{{environment}}-fss-pub.nais.io
    inbound:
      rules:
        - application: fp-swagger
          namespace: teamforeldrepenger
          cluster: {{environment}}-gcp
          permissions:
            scopes:
              - "swagger"
        - application: fpsak
          namespace: teamforeldrepenger
          cluster: {{environment}}-fss
