--------------------------------------------------------
--  DDL for Table DOKUMENT_HENDELSE
--------------------------------------------------------

CREATE TABLE DOKUMENT_HENDELSE
(
  ID                            bigint,
  BEHANDLING_ID                 bigint                                             NOT NULL,
  BEHANDLING_TYPE               VARCHAR(100),
  YTELSE_TYPE                   VARCHAR(100)                                       NOT NULL,
  DOKUMENT_MAL_NAVN             VARCHAR(7),
  GJELDER_VEDTAK                BOOLEAN      DEFAULT FALSE,
  FRITEKST                      TEXT,
  TITTEL                        VARCHAR(200),
  HISTORIKK_AKTOER              VARCHAR(100),
  REVURDERING_VARSLING_ARSAK    VARCHAR(100),
  OPPRETTET_AV                  VARCHAR(20)  DEFAULT 'VL',
  OPPRETTET_TID                 TIMESTAMP(3) DEFAULT localtimestamp,
  ENDRET_AV                     VARCHAR(20),
  ENDRET_TID                    TIMESTAMP(3),
  KL_BEHANDLING_TYPE            VARCHAR(100) DEFAULT 'BEHANDLING_TYPE'             NOT NULL,
  KL_YTELSE_TYPE                VARCHAR(100) DEFAULT 'FAGSAK_YTELSE'               NOT NULL,
  KL_HISTORIKK_AKTOER           VARCHAR(100) DEFAULT 'HISTORIKK_AKTOER'            NOT NULL,
  KL_REVURDERING_VARSLING_ARSAK VARCHAR(100) DEFAULT 'REVURDERING_VARSLING_AARSAK' NOT NULL,
  CONSTRAINT FK_DOKUMENT_HENDELSE_1 FOREIGN KEY (DOKUMENT_MAL_NAVN) REFERENCES DOKUMENT_MAL_TYPE (KODE),
  CONSTRAINT FK_DOKUMENT_HENDELSE_2 FOREIGN KEY (BEHANDLING_TYPE, KL_BEHANDLING_TYPE) REFERENCES KODELISTE (KODE, KODEVERK),
  CONSTRAINT FK_DOKUMENT_HENDELSE_3 FOREIGN KEY (YTELSE_TYPE, KL_YTELSE_TYPE) REFERENCES KODELISTE (KODE, KODEVERK),
  CONSTRAINT FK_DOKUMENT_HENDELSE_4 FOREIGN KEY (HISTORIKK_AKTOER, KL_HISTORIKK_AKTOER) REFERENCES KODELISTE (KODE, KODEVERK),
  CONSTRAINT FK_DOKUMENT_HENDELSE_5 FOREIGN KEY (REVURDERING_VARSLING_ARSAK, KL_REVURDERING_VARSLING_ARSAK) REFERENCES KODELISTE (KODE, KODEVERK)
);

CREATE INDEX IDX_DOKUMENT_HENDELSE_1 on DOKUMENT_HENDELSE (BEHANDLING_ID);
CREATE SEQUENCE SEQ_DOKUMENT_HENDELSE MINVALUE 1000000 MAXVALUE 999999999999999999 INCREMENT BY 50 START WITH 1003000 NO CYCLE;

ALTER TABLE DOKUMENT_HENDELSE
  ADD CONSTRAINT PK_HENDELSE PRIMARY KEY (ID);


COMMENT ON COLUMN DOKUMENT_HENDELSE.ID IS 'Primary Key';
COMMENT ON COLUMN DOKUMENT_HENDELSE.BEHANDLING_ID IS 'Id til tilhørende behandling i foreldrepengeløsningen';
COMMENT ON COLUMN DOKUMENT_HENDELSE.BEHANDLING_TYPE IS 'Behandlingstype  i foreldrepengeløsningen - kodeverk';
COMMENT ON COLUMN DOKUMENT_HENDELSE.YTELSE_TYPE IS 'Ytelse type til fagsaken i foreldrepengeløsningen - kodeverk';
COMMENT ON COLUMN DOKUMENT_HENDELSE.DOKUMENT_MAL_NAVN IS 'Navn på ønsket dokument';
COMMENT ON COLUMN DOKUMENT_HENDELSE.GJELDER_VEDTAK IS 'Om det er vedtaksdokument';
COMMENT ON COLUMN DOKUMENT_HENDELSE.FRITEKST IS 'Fritekst som skal vises i dokumentet';
COMMENT ON COLUMN DOKUMENT_HENDELSE.TITTEL IS 'Tittel for fritekstbrev';
COMMENT ON COLUMN DOKUMENT_HENDELSE.HISTORIKK_AKTOER IS 'FK:HISTORIKK_AKTOER Fremmednøkkel til';
COMMENT ON COLUMN DOKUMENT_HENDELSE.REVURDERING_VARSLING_ARSAK IS 'FK:REVURDERING_VARSLING_ARSAK Fremmednøkkel til';
COMMENT ON COLUMN DOKUMENT_HENDELSE.KL_YTELSE_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN DOKUMENT_HENDELSE.KL_BEHANDLING_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN DOKUMENT_HENDELSE.KL_HISTORIKK_AKTOER IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN DOKUMENT_HENDELSE.KL_REVURDERING_VARSLING_ARSAK IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON TABLE DOKUMENT_HENDELSE IS 'Hendelser om dokumenter bestilt eller forhåndvist fra foreldrepengeløsningen';
