CREATE TABLE EVENTMOTTAK_FEILLOGG
(
  ID                        BIGINT                                      NOT NULL,
  MELDING                   TEXT                                        NOT NULL,
  STATUS                    VARCHAR(100)                                NOT NULL,
  ANTALL_FEILEDE_FORSOK     INT          DEFAULT 0,
  SISTE_KJORING_TS          TIMESTAMP(3),
  FEILMELDING_SISTE_KJORING TEXT,
  KL_STATUS                 VARCHAR(100) DEFAULT ('EVENTMOTTAK_STATUS') NOT NULL,
  versjon                   INT          DEFAULT 0                      NOT NULL,
  opprettet_av              VARCHAR(20)  DEFAULT 'VL'                   NOT NULL,
  opprettet_tid             TIMESTAMP(3) DEFAULT localtimestamp         NOT NULL,
  endret_av                 VARCHAR(20),
  endret_tid                TIMESTAMP(3),
  CONSTRAINT PK_EVENTMOTTAK_FEILLOGG PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_EVENTMOTTAK_FEILLOGG MINVALUE 1000000 MAXVALUE 999999999999999999 INCREMENT BY 50 START WITH 1003000 NO CYCLE;

CREATE INDEX IDX_EVENTMOTTAK_FEILLOGG_1 on EVENTMOTTAK_FEILLOGG (STATUS);

CREATE INDEX IDX_EVENTMOTTAK_FEILLOGG_2 on EVENTMOTTAK_FEILLOGG (SISTE_KJORING_TS);

ALTER TABLE EVENTMOTTAK_FEILLOGG
  ADD CONSTRAINT FK_EVENTMOTTAK_FEILLOGG_1
    FOREIGN KEY (KL_STATUS, STATUS) REFERENCES KODELISTE (kodeverk, kode);

COMMENT ON TABLE EVENTMOTTAK_FEILLOGG is 'Feillogg for eventer som kommer fra fpsak';

COMMENT ON COLUMN EVENTMOTTAK_FEILLOGG.ID IS 'PK';
COMMENT ON COLUMN EVENTMOTTAK_FEILLOGG.MELDING IS 'Meldingen som kom fra eventkøen';
COMMENT ON COLUMN EVENTMOTTAK_FEILLOGG.STATUS IS 'Status for meldingen';
COMMENT ON COLUMN EVENTMOTTAK_FEILLOGG.ANTALL_FEILEDE_FORSOK IS 'Antallet feilede forsøk';
COMMENT ON COLUMN EVENTMOTTAK_FEILLOGG.SISTE_KJORING_TS IS 'Tidspunkt for siste kjøring';
COMMENT ON COLUMN EVENTMOTTAK_FEILLOGG.FEILMELDING_SISTE_KJORING IS 'Feilmelding for siste kjøring';