--------------------------------------------------------
--  DDL for Table SAKSBEHANDLER_TEKST
--------------------------------------------------------

CREATE TABLE SAKSBEHANDLER_TEKST
(
    ID              BIGINT,
    BEHANDLING_UUID UUID                                NOT NULL,
    AVKLAR_FRITEKST VARCHAR(1500),
    TITTEL          VARCHAR(200),
    FRITEKST        TEXT,
    VEDTAKSBREV     VARCHAR(100)                        NOT NULL,
    KL_VEDTAKSBREV  VARCHAR(100) DEFAULT 'VEDTAKSBREV'  NOT NULL,
    OPPRETTET_AV    VARCHAR(20)  DEFAULT 'VL'           NOT NULL,
    OPPRETTET_TID   TIMESTAMP(3) DEFAULT localtimestamp NOT NULL,
    ENDRET_AV       VARCHAR(20),
    ENDRET_TID      TIMESTAMP(3),
    CONSTRAINT PK_SAKSBEHANDLER_TEKST PRIMARY KEY (ID),
    CONSTRAINT FK_SAKSBEHANDLER_TEKST_1 FOREIGN KEY (VEDTAKSBREV, KL_VEDTAKSBREV) REFERENCES KODELISTE (KODE, KODEVERK)
);
CREATE INDEX IDX_SAKSBEHANDLER_TEKST_1 ON SAKSBEHANDLER_TEKST (BEHANDLING_UUID);
CREATE SEQUENCE SEQ_SAKSBEHANDLER_TEKST MINVALUE 1000000 MAXVALUE 999999999999999999 INCREMENT BY 50 START WITH 1003000 NO CYCLE;

COMMENT ON COLUMN SAKSBEHANDLER_TEKST.ID IS 'Primary Key';
COMMENT ON COLUMN SAKSBEHANDLER_TEKST.BEHANDLING_UUID IS 'UUID til tilhørende behandling i foreldrepengeløsningen';
COMMENT ON COLUMN SAKSBEHANDLER_TEKST.AVKLAR_FRITEKST IS 'Begrunnelse for avslag av søknad.';
COMMENT ON COLUMN SAKSBEHANDLER_TEKST.FRITEKST IS 'Fritekst som skal vises i dokumentet';
COMMENT ON COLUMN SAKSBEHANDLER_TEKST.TITTEL IS 'Tittel felt brukt som hovedoverskrift i frikestbrev';
COMMENT ON COLUMN SAKSBEHANDLER_TEKST.FRITEKST IS 'Fritekst felt brukt som hovedoverskrift i frikestbrev';
COMMENT ON COLUMN SAKSBEHANDLER_TEKST.VEDTAKSBREV IS 'FK: VEDTAKSBREV';
COMMENT ON COLUMN SAKSBEHANDLER_TEKST.KL_VEDTAKSBREV IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON TABLE SAKSBEHANDLER_TEKST IS 'Tekst data angitt fra saksbehandler.';
