CREATE TABLE KONFIG_VERDI
(
  ID            bigint,
  KONFIG_KODE   VARCHAR(50),
  KONFIG_GRUPPE VARCHAR(100),
  KONFIG_VERDI  VARCHAR(255),
  GYLDIG_FOM    DATE         DEFAULT current_timestamp,
  GYLDIG_TOM    DATE         DEFAULT to_date('31.12.9999', 'dd.mm.yyyy'),
  OPPRETTET_AV  VARCHAR(20)  DEFAULT 'VL',
  OPPRETTET_TID TIMESTAMP(3) DEFAULT localtimestamp,
  ENDRET_AV     VARCHAR(20),
  ENDRET_TID    TIMESTAMP(3)
);

CREATE SEQUENCE SEQ_KONFIG_VERDI MINVALUE 1000000 MAXVALUE 999999999999999999 INCREMENT BY 50 START WITH 1002900 NO CYCLE;

COMMENT ON COLUMN KONFIG_VERDI.ID IS 'Primary Key';
COMMENT ON COLUMN KONFIG_VERDI.KONFIG_KODE IS 'Angir kode som identifiserer en konfigurerbar verdi. ';
COMMENT ON COLUMN KONFIG_VERDI.KONFIG_GRUPPE IS 'Angir gruppe en konfigurerbar verdi kode tilhører (hvis noen - kan også spesifiseres som INGEN).';
COMMENT ON COLUMN KONFIG_VERDI.KONFIG_VERDI IS 'Angir verdi';
COMMENT ON COLUMN KONFIG_VERDI.GYLDIG_FOM IS 'Gydlig fra-og-med dato';
COMMENT ON COLUMN KONFIG_VERDI.GYLDIG_TOM IS 'Gydlig til-og-med dato';
COMMENT ON TABLE KONFIG_VERDI IS 'Angir konfigurerbare verdier med kode, eventuelt tilhørende gruppe.';

CREATE TABLE KONFIG_VERDI_KODE
(
  KODE                   VARCHAR(50),
  KONFIG_GRUPPE          VARCHAR(100) DEFAULT 'INGEN',
  NAVN                   VARCHAR(50),
  KONFIG_TYPE            VARCHAR(100),
  BESKRIVELSE            VARCHAR(255),
  OPPRETTET_AV           VARCHAR(20)  DEFAULT 'VL',
  OPPRETTET_TID          TIMESTAMP(3) DEFAULT current_timestamp,
  ENDRET_AV              VARCHAR(20),
  ENDRET_TID             TIMESTAMP(3),
  KL_KONFIG_VERDI_TYPE   VARCHAR(100) DEFAULT 'KONFIG_VERDI_TYPE' /*GENERATED*/ ,
  KL_KONFIG_VERDI_GRUPPE VARCHAR(100) DEFAULT 'KONFIG_VERDI_GRUPPE' /*GENERATED*/
);

ALTER TABLE KONFIG_VERDI_KODE
  ADD CONSTRAINT FK_KONFIG_VERDI_KODE_80 FOREIGN KEY (KONFIG_TYPE, KL_KONFIG_VERDI_TYPE)
    REFERENCES KODELISTE (KODE, KODEVERK);
ALTER TABLE KONFIG_VERDI_KODE
  ADD CONSTRAINT FK_KONFIG_VERDI_KODE_81 FOREIGN KEY (KONFIG_GRUPPE, KL_KONFIG_VERDI_GRUPPE)
    REFERENCES KODELISTE (KODE, KODEVERK);

create index IDX_KONFIG_VERDI_KODE_1 on KONFIG_VERDI_KODE (KONFIG_TYPE);
create index IDX_KONFIG_VERDI_KODE_2 on KONFIG_VERDI_KODE (KONFIG_GRUPPE);

COMMENT ON COLUMN KONFIG_VERDI_KODE.KODE IS 'Primary Key';
COMMENT ON COLUMN KONFIG_VERDI_KODE.KONFIG_GRUPPE IS 'Angir gruppe en konfigurerbar verdi kode tilhører (hvis noen - kan også spesifiseres som INGEN).';
COMMENT ON COLUMN KONFIG_VERDI_KODE.NAVN IS 'Angir et visningsnavn';
COMMENT ON COLUMN KONFIG_VERDI_KODE.KONFIG_TYPE IS 'Type angivelse for koden';
COMMENT ON COLUMN KONFIG_VERDI_KODE.BESKRIVELSE IS 'Beskrivelse av formÃ¥let den konfigurerbare verdien';
COMMENT ON COLUMN KONFIG_VERDI_KODE.KL_KONFIG_VERDI_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN KONFIG_VERDI_KODE.KL_KONFIG_VERDI_GRUPPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON TABLE KONFIG_VERDI_KODE IS 'Angir unik kode for en konfigurerbar verdi for validering og utlisting av tilgjengelige koder.';


CREATE INDEX IDX_KONFIG_VERDI_1
  ON KONFIG_VERDI (GYLDIG_FOM, GYLDIG_TOM);
CREATE INDEX IDX_KONFIG_VERDI_3
  ON KONFIG_VERDI (KONFIG_KODE);
CREATE INDEX IDX_KONFIG_VERDI_2
  ON KONFIG_VERDI (KONFIG_GRUPPE);
CREATE UNIQUE INDEX UIDX_KONFIG_VERDI_1
  ON KONFIG_VERDI (KONFIG_GRUPPE, GYLDIG_TOM, KONFIG_KODE);

ALTER TABLE KONFIG_VERDI
  ADD CONSTRAINT PK_KONFIG_VERDI PRIMARY KEY (ID);
ALTER TABLE KONFIG_VERDI
  ALTER COLUMN OPPRETTET_TID SET NOT NULL;
ALTER TABLE KONFIG_VERDI
  ALTER COLUMN OPPRETTET_AV SET NOT NULL;
ALTER TABLE KONFIG_VERDI
  ALTER COLUMN GYLDIG_TOM SET NOT NULL;
ALTER TABLE KONFIG_VERDI
  ALTER COLUMN GYLDIG_FOM SET NOT NULL;
ALTER TABLE KONFIG_VERDI
  ALTER COLUMN KONFIG_GRUPPE SET NOT NULL;
ALTER TABLE KONFIG_VERDI
  ALTER COLUMN KONFIG_KODE SET NOT NULL;
ALTER TABLE KONFIG_VERDI
  ALTER COLUMN ID SET NOT NULL;

ALTER TABLE KONFIG_VERDI_KODE
  ADD CONSTRAINT PK_KONFIG_VERDI_KODE PRIMARY KEY (KODE, KONFIG_GRUPPE);
ALTER TABLE KONFIG_VERDI_KODE
  ALTER COLUMN OPPRETTET_TID SET NOT NULL;
ALTER TABLE KONFIG_VERDI_KODE
  ALTER COLUMN OPPRETTET_AV SET NOT NULL;
ALTER TABLE KONFIG_VERDI_KODE
  ALTER COLUMN KONFIG_TYPE SET NOT NULL;
ALTER TABLE KONFIG_VERDI_KODE
  ALTER COLUMN NAVN SET NOT NULL;
ALTER TABLE KONFIG_VERDI_KODE
  ALTER COLUMN KONFIG_GRUPPE SET NOT NULL;
ALTER TABLE KONFIG_VERDI_KODE
  ALTER COLUMN KODE SET NOT NULL;

ALTER TABLE KONFIG_VERDI
  ADD CONSTRAINT FK_KONFIG_VERDI_1 FOREIGN KEY (KONFIG_KODE, KONFIG_GRUPPE)
    REFERENCES KONFIG_VERDI_KODE (KODE, KONFIG_GRUPPE);
