Insert into DOKUMENT_MAL_TYPE (KODE, NAVN, TILGJENGELIG_MANUELL_UTSENDELSE, DOKUMENT_MAL_RESTRIKSJON, DOKSYS_KODE)
values ('INNHEN', 'Innhent dokumentasjon', 'J', 'INGEN', '000049');
Insert into DOKUMENT_MAL_TYPE (KODE, NAVN, TILGJENGELIG_MANUELL_UTSENDELSE, DOKUMENT_MAL_RESTRIKSJON, DOKSYS_KODE)
values ('POSVED', 'Positivt vedtaksbrev', 'N', 'INGEN', '000048');
Insert into DOKUMENT_MAL_TYPE (KODE, NAVN, TILGJENGELIG_MANUELL_UTSENDELSE, DOKUMENT_MAL_RESTRIKSJON, DOKSYS_KODE)
values ('HENLEG', 'Behandling henlagt', 'N', 'INGEN', '000050');
Insert into DOKUMENT_MAL_TYPE (KODE, NAVN, TILGJENGELIG_MANUELL_UTSENDELSE, DOKUMENT_MAL_RESTRIKSJON, DOKSYS_KODE)
values ('AVSLAG', 'Avslagsbrev', 'N', 'INGEN', '000051');
Insert into DOKUMENT_MAL_TYPE (KODE, NAVN, TILGJENGELIG_MANUELL_UTSENDELSE, DOKUMENT_MAL_RESTRIKSJON, DOKSYS_KODE)
values ('UENDRE', 'Uendret utfall', 'N', 'INGEN', '000052');
Insert into DOKUMENT_MAL_TYPE (KODE, NAVN, TILGJENGELIG_MANUELL_UTSENDELSE, DOKUMENT_MAL_RESTRIKSJON, DOKSYS_KODE)
values ('REVURD', 'Varsel om revurdering', 'J', 'REVURDERING', '000058');
Insert into DOKUMENT_MAL_TYPE (KODE, NAVN, TILGJENGELIG_MANUELL_UTSENDELSE, DOKUMENT_MAL_RESTRIKSJON, DOKSYS_KODE)
values ('FORLEN', 'Forlenget saksbehandlingstid', 'J', 'ÅPEN_BEHANDLING', '000056');
Insert into DOKUMENT_MAL_TYPE (KODE, NAVN, TILGJENGELIG_MANUELL_UTSENDELSE, DOKUMENT_MAL_RESTRIKSJON, DOKSYS_KODE)
values ('FORLME', 'Forlenget saksbehandlingstid - medlemskap', 'J', 'ÅPEN_BEHANDLING_IKKE_SENDT', '000056');
Insert into DOKUMENT_MAL_TYPE (KODE, NAVN, TILGJENGELIG_MANUELL_UTSENDELSE, DOKUMENT_MAL_RESTRIKSJON, DOKSYS_KODE)
values ('KLAGAV', 'Vedtak om avvist klage', 'N', 'INGEN', '000054');
Insert into DOKUMENT_MAL_TYPE (KODE, NAVN, TILGJENGELIG_MANUELL_UTSENDELSE, DOKUMENT_MAL_RESTRIKSJON, DOKSYS_KODE)
values ('KLAGVE', 'Vedtak om stadfestelse', 'N', 'INGEN', '000055');
Insert into DOKUMENT_MAL_TYPE (KODE, NAVN, TILGJENGELIG_MANUELL_UTSENDELSE, DOKUMENT_MAL_RESTRIKSJON, DOKSYS_KODE)
values ('KLAGNY', 'Vedtak opphevet, sendt til ny behandling', 'N', 'INGEN', '000059');
Insert into DOKUMENT_MAL_TYPE (KODE, NAVN, TILGJENGELIG_MANUELL_UTSENDELSE, DOKUMENT_MAL_RESTRIKSJON, DOKSYS_KODE)
values ('KLAGOV', 'Overføring til NAV Klageinstans', 'N', 'INGEN', '000060');
Insert into DOKUMENT_MAL_TYPE (KODE, NAVN, TILGJENGELIG_MANUELL_UTSENDELSE, DOKUMENT_MAL_RESTRIKSJON, DOKSYS_KODE)
values ('INSSKR', 'Svar på innsynskrav', 'N', 'INGEN', '000071');
Insert into DOKUMENT_MAL_TYPE (KODE, NAVN, TILGJENGELIG_MANUELL_UTSENDELSE, DOKUMENT_MAL_RESTRIKSJON, DOKSYS_KODE)
values ('INNVFP', 'Innvilgelsesbrev Foreldrepenger', 'N', 'INGEN', '000061');
Insert into DOKUMENT_MAL_TYPE (KODE, NAVN, TILGJENGELIG_MANUELL_UTSENDELSE, DOKUMENT_MAL_RESTRIKSJON, DOKSYS_KODE)
values ('OPPHOR', 'Opphør brev', 'N', 'INGEN', '000085');
Insert into DOKUMENT_MAL_TYPE (KODE, NAVN, TILGJENGELIG_MANUELL_UTSENDELSE, DOKUMENT_MAL_RESTRIKSJON, DOKSYS_KODE)
values ('INNTID', 'Ikke mottatt søknad', 'N', 'INGEN', '000091');
Insert into DOKUMENT_MAL_TYPE (KODE, NAVN, TILGJENGELIG_MANUELL_UTSENDELSE, DOKUMENT_MAL_RESTRIKSJON, DOKSYS_KODE)
values ('AVSLFP', 'Avslagsbrev Foreldrepenger', 'N', 'INGEN', '000080');
Insert into DOKUMENT_MAL_TYPE (KODE, NAVN, TILGJENGELIG_MANUELL_UTSENDELSE, DOKUMENT_MAL_RESTRIKSJON, DOKSYS_KODE)
values ('FRITKS', 'Fritekstbrev', 'N', 'INGEN', '000096');
Insert into DOKUMENT_MAL_TYPE (KODE, NAVN, TILGJENGELIG_MANUELL_UTSENDELSE, DOKUMENT_MAL_RESTRIKSJON, DOKSYS_KODE)
values ('FORLTS', 'Forlenget saksbehandlingstid - Tidlig søknad', 'N', 'ÅPEN_BEHANDLING', '000056');
Insert into DOKUMENT_MAL_TYPE (KODE, NAVN, TILGJENGELIG_MANUELL_UTSENDELSE, DOKUMENT_MAL_RESTRIKSJON, DOKSYS_KODE)
values ('FOROPT', 'Forlenget saksbehandlingstid - Venter Opptjening', 'N', 'ÅPEN_BEHANDLING', '000056');
Insert into DOKUMENT_MAL_TYPE (KODE, NAVN, TILGJENGELIG_MANUELL_UTSENDELSE, DOKUMENT_MAL_RESTRIKSJON, DOKSYS_KODE)
values ('VEDMED', 'Vedtak om mehold', 'N', 'INGEN', '000114');
