Insert into DOKUMENT_MAL_TYPE (KODE, NAVN, TILGJENGELIG_MANUELL_UTSENDELSE, DOKUMENT_MAL_RESTRIKSJON, DOKSYS_KODE)
values ('KSTADF', 'Vedtak om stadfestelse i klagesak', 'N', 'INGEN', '000096');

Insert into DOKUMENT_MAL_TYPE (KODE, NAVN, TILGJENGELIG_MANUELL_UTSENDELSE, DOKUMENT_MAL_RESTRIKSJON, DOKSYS_KODE)
values ('KAVVIS', 'Vedtak om avvist klage', 'N', 'INGEN', '000096');

Insert into DOKUMENT_MAL_TYPE (KODE, NAVN, TILGJENGELIG_MANUELL_UTSENDELSE, DOKUMENT_MAL_RESTRIKSJON, DOKSYS_KODE)
values ('KOMGJO', 'Vedtak om omgjøring av klage', 'N', 'INGEN', '000096');

Insert into DOKUMENT_MAL_TYPE (KODE, NAVN, TILGJENGELIG_MANUELL_UTSENDELSE, DOKUMENT_MAL_RESTRIKSJON, DOKSYS_KODE)
values ('KOVKLA', 'Klage oversendt til klageinstans', 'N', 'INGEN', '000096');
