CREATE TABLE KODELISTE_RELASJON
(
  ID            bigint,
  KODEVERK1     VARCHAR(100),
  KODE1         VARCHAR(100),
  KODEVERK2     VARCHAR(100),
  KODE2         VARCHAR(100),
  GYLDIG_FOM    DATE         DEFAULT current_timestamp,
  GYLDIG_TOM    DATE         DEFAULT TO_DATE('31.12.9999', 'DD.MM.YYYY'),
  OPPRETTET_AV  VARCHAR(20)  DEFAULT 'VL',
  OPPRETTET_TID TIMESTAMP(3) DEFAULT localtimestamp,
  ENDRET_AV     VARCHAR(20),
  ENDRET_TID    TIMESTAMP(3)
);

COMMENT ON COLUMN KODELISTE_RELASJON.ID IS 'Primary Key';
COMMENT ON COLUMN KODELISTE_RELASJON.KODEVERK1 IS 'Kodeverk for kode 1';
COMMENT ON COLUMN KODELISTE_RELASJON.KODE1 IS 'Kode 1';
COMMENT ON COLUMN KODELISTE_RELASJON.KODEVERK2 IS 'Kodeverk for kode 2';
COMMENT ON COLUMN KODELISTE_RELASJON.KODE2 IS 'Kode 2';
COMMENT ON COLUMN KODELISTE_RELASJON.GYLDIG_FOM IS 'Gyldig fra og med dato';
COMMENT ON COLUMN KODELISTE_RELASJON.GYLDIG_TOM IS 'Gyldig til og med dato';
COMMENT ON TABLE KODELISTE_RELASJON IS 'Relasjon mellom kodeliste elementer: kode1 og kode2';

CREATE SEQUENCE SEQ_KODELISTE_RELASJON MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 50 START WITH 1008850 NO CYCLE;


ALTER TABLE KODELISTE_RELASJON
  ADD CONSTRAINT FK_KODELISTE_RELASJON_1 FOREIGN KEY (KODE1, KODEVERK1)
    REFERENCES KODELISTE (KODE, KODEVERK);
ALTER TABLE KODELISTE_RELASJON
  ADD CONSTRAINT FK_KODELISTE_RELASJON_2 FOREIGN KEY (KODE2, KODEVERK2)
    REFERENCES KODELISTE (KODE, KODEVERK);


ALTER TABLE KODELISTE_RELASJON
  ADD CONSTRAINT PK_KODELISTE_RELASJON PRIMARY KEY (ID);
ALTER TABLE KODELISTE_RELASJON
  ALTER COLUMN OPPRETTET_TID SET NOT NULL;
ALTER TABLE KODELISTE_RELASJON
  ALTER COLUMN OPPRETTET_AV SET NOT NULL;
ALTER TABLE KODELISTE_RELASJON
  ALTER COLUMN GYLDIG_TOM SET NOT NULL;
ALTER TABLE KODELISTE_RELASJON
  ALTER COLUMN GYLDIG_FOM SET NOT NULL;
ALTER TABLE KODELISTE_RELASJON
  ALTER COLUMN KODE2 SET NOT NULL;
ALTER TABLE KODELISTE_RELASJON
  ALTER COLUMN KODEVERK2 SET NOT NULL;
ALTER TABLE KODELISTE_RELASJON
  ALTER COLUMN KODE1 SET NOT NULL;
ALTER TABLE KODELISTE_RELASJON
  ALTER COLUMN KODEVERK1 SET NOT NULL;
ALTER TABLE KODELISTE_RELASJON
  ALTER COLUMN ID SET NOT NULL;
ALTER TABLE KODELISTE_RELASJON
  ADD CONSTRAINT UIDX_KODELISTE_RELASJON_1 UNIQUE (KODEVERK1, KODE1, KODEVERK2, KODE2);

