CREATE TABLE DOKUMENT_HISTORIKK_INNSLAG
(
  ID                 BIGINT                               NOT NULL,
  BEHANDLING_ID      BIGINT                               NOT NULL,
  JOURNALPOST_ID     VARCHAR(20)                          NOT NULL,
  HISTORIKK_AKTOER   VARCHAR(100),
  DOKUMENT_ID        VARCHAR(20)                          NOT NULL,
  KL_HISTORIKK_AKTOR VARCHAR(100) DEFAULT 'FAGSAK_YTELSE' NOT NULL,
  VERSJON            INT          DEFAULT 0               NOT NULL,
  OPPRETTET_AV       VARCHAR(20)  DEFAULT 'VL'            NOT NULL,
  OPPRETTET_TID      TIMESTAMP(3) DEFAULT LOCALTIMESTAMP  NOT NULL,
  ENDRET_AV          VARCHAR(20),
  ENDRET_TID         TIMESTAMP(3),
  CONSTRAINT PK_DOKUMENT_HISTORIKK_INNSLAG PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DOKUMENT_HISTORIKK_INNSLAG MINVALUE 1000000 MAXVALUE 999999999999999999 INCREMENT BY 50 START WITH 1003000 NO CYCLE;

CREATE INDEX IDX_DOKUMENT_HISTORIKK_INNSLAG_1 on DOKUMENT_HISTORIKK_INNSLAG (BEHANDLING_ID);
CREATE INDEX IDX_DOKUMENT_HISTORIKK_INNSLAG_2 on DOKUMENT_HISTORIKK_INNSLAG (JOURNALPOST_ID);
CREATE INDEX IDX_DOKUMENT_HISTORIKK_INNSLAG_3 on DOKUMENT_HISTORIKK_INNSLAG (DOKUMENT_ID);

ALTER TABLE DOKUMENT_HISTORIKK_INNSLAG
  ADD CONSTRAINT FK_DOKUMENT_HISTORIKK_INNSLAG_1
    FOREIGN KEY (KL_HISTORIKK_AKTOR, HISTORIKK_AKTOER) REFERENCES KODELISTE (kodeverk, kode);

COMMENT ON TABLE DOKUMENT_HISTORIKK_INNSLAG is 'Historikk for bestilte dokumenter';

COMMENT ON COLUMN DOKUMENT_HISTORIKK_INNSLAG.ID IS 'PK';
COMMENT ON COLUMN DOKUMENT_HISTORIKK_INNSLAG.BEHANDLING_ID IS 'Behandlingen dokumentet gjelder';
COMMENT ON COLUMN DOKUMENT_HISTORIKK_INNSLAG.JOURNALPOST_ID IS 'Dokumentets JournalpostID i joark';
COMMENT ON COLUMN DOKUMENT_HISTORIKK_INNSLAG.HISTORIKK_AKTOER IS 'Kodeverk, hvem som bestilte dokumentet';
COMMENT ON COLUMN DOKUMENT_HISTORIKK_INNSLAG.DOKUMENT_ID IS 'Dokumentets Dokument ID i JOARK';
COMMENT ON COLUMN DOKUMENT_HISTORIKK_INNSLAG.KL_HISTORIKK_AKTOR IS 'Kodeliste';