--------------------------------------------------------
--  DDL for Table DOKUMENT_MAL_TYPE
--------------------------------------------------------

CREATE TABLE DOKUMENT_MAL_TYPE
(
  KODE                            VARCHAR(7)                          NOT NULL,
  NAVN                            VARCHAR(50)                         NOT NULL,
  BESKRIVELSE                     VARCHAR(4000),
  OPPRETTET_AV                    VARCHAR(20)  DEFAULT 'VL'           NOT NULL,
  OPPRETTET_TID                   TIMESTAMP(3) DEFAULT localtimestamp NOT NULL,
  ENDRET_AV                       VARCHAR(20),
  ENDRET_TID                      TIMESTAMP(3),
  TILGJENGELIG_MANUELL_UTSENDELSE VARCHAR(1)   DEFAULT 'J'            NOT NULL,
  DOKUMENT_MAL_RESTRIKSJON        VARCHAR(100) DEFAULT 'INGEN'        NOT NULL,
  DOKSYS_KODE                     VARCHAR(20)  DEFAULT 'INGEN'        NOT NULL,
  KL_DOKUMENT_MAL_RESTRIKSJON     VARCHAR(100) DEFAULT 'DOKUMENT_MAL_RESTRIKSJON', /*GENERATED*/
  CONSTRAINT PK_DOKUMENT_MAL_TYPE PRIMARY KEY (KODE),
  CONSTRAINT FK_DOKUMENT_MAL_TYPE_1 FOREIGN KEY (DOKUMENT_MAL_RESTRIKSJON, KL_DOKUMENT_MAL_RESTRIKSJON) REFERENCES KODELISTE (KODE, KODEVERK)
);

CREATE INDEX IDX_DOKUMENT_MAL_TYPE_1 ON DOKUMENT_MAL_TYPE (DOKUMENT_MAL_RESTRIKSJON);

ALTER TABLE DOKUMENT_MAL_TYPE
  ADD CONSTRAINT CHK_TILGJENGELIG_MANUELL_UTSENDELSE CHECK (TILGJENGELIG_MANUELL_UTSENDELSE in ('J', 'N'));

COMMENT ON COLUMN DOKUMENT_MAL_TYPE.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN DOKUMENT_MAL_TYPE.NAVN IS 'Lesbart navn på dokumentmaltype';
COMMENT ON COLUMN DOKUMENT_MAL_TYPE.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN DOKUMENT_MAL_TYPE.TILGJENGELIG_MANUELL_UTSENDELSE IS 'Kan dokumentmalen benyttes for informasjonsinnhenting i GUI (Y) eller ikke (N)';
COMMENT ON COLUMN DOKUMENT_MAL_TYPE.DOKUMENT_MAL_RESTRIKSJON IS 'Restriksjonskode som begrenser bruken av dokumentmalen, eller INGEN';
COMMENT ON COLUMN DOKUMENT_MAL_TYPE.DOKSYS_KODE IS 'Doksys kodeverkskode';
COMMENT ON COLUMN DOKUMENT_MAL_TYPE.KL_DOKUMENT_MAL_RESTRIKSJON IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON TABLE DOKUMENT_MAL_TYPE IS 'Angir definerte dokumentmaler som brukes ved brevproduksjon';

--------------------------------------------------------
--  DDL for Table DOKUMENT_DATA
--------------------------------------------------------

CREATE TABLE DOKUMENT_DATA
(
  ID                bigint                              NOT NULL,
  BEHANDLING_ID     bigint                              NOT NULL,
  DOKUMENT_MAL_NAVN VARCHAR(7)                          NOT NULL,
  FORHAANDSVIST_TID TIMESTAMP(3),
  SENDT_TID         TIMESTAMP(3),
  VERSJON           bigint       DEFAULT 0              NOT NULL,
  OPPRETTET_AV      VARCHAR(20)  DEFAULT 'VL'           NOT NULL,
  OPPRETTET_TID     TIMESTAMP(3) DEFAULT localtimestamp NOT NULL,
  ENDRET_AV         VARCHAR(20),
  ENDRET_TID        TIMESTAMP(3),
  BESTILT_TID       TIMESTAMP(3),
  CONSTRAINT PK_DOKUMENT_DATA PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DOKUMENT_DATA MINVALUE 1000000 MAXVALUE 999999999999999999 INCREMENT BY 50 START WITH 1003000 NO CYCLE;

CREATE INDEX IDX_DOKUMENT_DATA_6 ON DOKUMENT_DATA (DOKUMENT_MAL_NAVN);
CREATE INDEX IDX_DOKUMENT_DATA_2 ON DOKUMENT_DATA (BEHANDLING_ID);

--ALTER TABLE DOKUMENT_DATA ADD CONSTRAINT FK_DOKUMENT_DATA_2 FOREIGN KEY (BEHANDLING_ID) REFERENCES BEHANDLING (ID);
ALTER TABLE DOKUMENT_DATA
  ADD CONSTRAINT FK_DOKUMENT_DATA_3 FOREIGN KEY (DOKUMENT_MAL_NAVN) REFERENCES DOKUMENT_MAL_TYPE (KODE);

COMMENT ON COLUMN DOKUMENT_DATA.ID IS 'Primary Key';
COMMENT ON COLUMN DOKUMENT_DATA.BEHANDLING_ID IS 'BEHANDLING Fremmednøkkel for kobling til behandling';
COMMENT ON COLUMN DOKUMENT_DATA.DOKUMENT_MAL_NAVN IS 'Navn på mal som brevet er lages fra.';
COMMENT ON COLUMN DOKUMENT_DATA.FORHAANDSVIST_TID IS 'Tidspunkt for forhåndsvisning.';
COMMENT ON COLUMN DOKUMENT_DATA.SENDT_TID IS 'Tidspunkt for oversendelse til brevløsningen.';
COMMENT ON COLUMN DOKUMENT_DATA.BESTILT_TID IS 'Tidspunkt dokumentet ble bestilt';
COMMENT ON TABLE DOKUMENT_DATA IS 'Dokumentdata innholder informasjon om et brev som skal bestilles, eller som er bestilt.';

-- Tabell DOKUMENT_FELLES
--------------------------------------------------------
--  DDL for Table DOKUMENT_FELLES
--------------------------------------------------------

CREATE TABLE DOKUMENT_FELLES
(
  ID                       bigint,
  VERSJON                  bigint       DEFAULT 0               NOT NULL,
  SPRAK_KODE               VARCHAR(100)                         NOT NULL,
  SAKSNUMMER               bigint                               NOT NULL,
  SIGN_SAKSBEHANDLER_NAVN  VARCHAR(80),
  AUTOMATISK_BEHANDLET     VARCHAR(1)                           NOT NULL,
  SAKSPART_ID              VARCHAR(20)                          NOT NULL,
  SAKSPART_NAVN            VARCHAR(80)                          NOT NULL,
  SIGN_BESLUTTER_NAVN      VARCHAR(80),
  SIGN_BESLUTTER_GEO_ENHET VARCHAR(80),
  MOTTAKER_ID              VARCHAR(20)                          NOT NULL,
  MOTTAKER_NAVN            VARCHAR(80)                          NOT NULL,
  NAVN_AVSENDER_ENHET      VARCHAR(80)                          NOT NULL,
  NUMMER_AVSENDER_ENHET    VARCHAR(80),
  KONTAKT_TLF              VARCHAR(80)                          NOT NULL,
  DOKUMENT_DATO            TIMESTAMP(3)                         NOT NULL,
  OPPRETTET_AV             VARCHAR(20)  DEFAULT 'VL'            NOT NULL,
  OPPRETTET_TID            TIMESTAMP(3) DEFAULT localtimestamp  NOT NULL,
  ENDRET_AV                VARCHAR(20),
  ENDRET_TID               TIMESTAMP(3),
  KL_SPRAAK_KODE           VARCHAR(100) DEFAULT ('SPRAAK_KODE') NOT NULL,
  DOKUMENT_DATA_ID         bigint                               NOT NULL,
  DOKUMENT_ID              VARCHAR(20),
  JOURNALPOST_ID           VARCHAR(20),
  SAKSPART_PERSON_STATUS   VARCHAR(20)  DEFAULT 'ANNET'         NOT NULL,
  CONSTRAINT PK_DOKUMENT_FELLES PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DOKUMENT_FELLES MINVALUE 1000000 MAXVALUE 999999999999999999 INCREMENT BY 50 START WITH 1003000 NO CYCLE;

CREATE INDEX IDX_DOKUMENT_FELLES_9 ON DOKUMENT_FELLES (DOKUMENT_DATA_ID);
CREATE INDEX IDX_DOKUMENT_FELLES_10 ON DOKUMENT_FELLES (SPRAK_KODE);

ALTER TABLE DOKUMENT_FELLES
  ADD CONSTRAINT CHK_AUTOMATISK_BEHANDLET CHECK (AUTOMATISK_BEHANDLET in ('J', 'N'));

ALTER TABLE DOKUMENT_FELLES
  ADD CONSTRAINT FK_DOKUMENT_FELLES_4 FOREIGN KEY (DOKUMENT_DATA_ID) REFERENCES DOKUMENT_DATA (ID);
ALTER TABLE DOKUMENT_FELLES
  ADD CONSTRAINT FK_DOKUMENT_FELLES_80 FOREIGN KEY (SPRAK_KODE, KL_SPRAAK_KODE) REFERENCES KODELISTE (KODE, KODEVERK);

COMMENT ON COLUMN DOKUMENT_FELLES.ID IS 'Primary Key';
COMMENT ON COLUMN DOKUMENT_FELLES.SPRAK_KODE IS 'FK:SPRAAK_KODE Brukers foretrukne språk som skal brukes i kommunikasjon med bruker';
COMMENT ON COLUMN DOKUMENT_FELLES.SAKSNUMMER IS 'Saksnummer i GSAK';
COMMENT ON COLUMN DOKUMENT_FELLES.SIGN_SAKSBEHANDLER_NAVN IS 'Signerende saksbehandlers navn';
COMMENT ON COLUMN DOKUMENT_FELLES.AUTOMATISK_BEHANDLET IS 'Er saken blitt automatisk behandlet?';
COMMENT ON COLUMN DOKUMENT_FELLES.SAKSPART_ID IS 'Fødselsnummer eller D-nummer til bruker saken gjelder';
COMMENT ON COLUMN DOKUMENT_FELLES.SAKSPART_NAVN IS 'Navn på bruker saken gjelder';
COMMENT ON COLUMN DOKUMENT_FELLES.SIGN_BESLUTTER_NAVN IS 'Signerende beslutters navn';
COMMENT ON COLUMN DOKUMENT_FELLES.SIGN_BESLUTTER_GEO_ENHET IS 'Navn på signerende beslutters geografiske enhet';
COMMENT ON COLUMN DOKUMENT_FELLES.MOTTAKER_ID IS 'Fødselsnummer eller D-nummer til dokumentmottaker';
COMMENT ON COLUMN DOKUMENT_FELLES.MOTTAKER_NAVN IS 'Navn på adressat';
COMMENT ON COLUMN DOKUMENT_FELLES.NAVN_AVSENDER_ENHET IS 'Navn på NAV-enhet som har sendt dokumentet';
COMMENT ON COLUMN DOKUMENT_FELLES.NUMMER_AVSENDER_ENHET IS 'ID til NAV-enhet som har sendt dokumentet';
COMMENT ON COLUMN DOKUMENT_FELLES.KONTAKT_TLF IS 'Dokumentmottakers kontaktnummer';
COMMENT ON COLUMN DOKUMENT_FELLES.DOKUMENT_DATO IS 'Dato dokumentet er produsert';
COMMENT ON COLUMN DOKUMENT_FELLES.KL_SPRAAK_KODE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN DOKUMENT_FELLES.DOKUMENT_DATA_ID IS 'FK:DOKUMENT_DATA Fremmednøkkel til tabellen som Inneholder informasjon om hvilken dokumentmal som er bestillt og når brevet er bestillt';
COMMENT ON COLUMN DOKUMENT_FELLES.DOKUMENT_ID IS 'Dokumentets Dokument ID i JOARK';
COMMENT ON COLUMN DOKUMENT_FELLES.JOURNALPOST_ID IS 'Journalpostens ID i JOARK';
COMMENT ON COLUMN DOKUMENT_FELLES.SAKSPART_PERSON_STATUS IS 'Gjeldende personstatus fra TPS når dokumentet produseres';
COMMENT ON TABLE DOKUMENT_FELLES IS 'Generell informasjon tilhørende en brevutsendelse';
