name: Oppdaterer deployment issue

on:
  repository_dispatch:
    types: [update-issue]

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Test success
        if: github.event.client_payload.success == 'true' && github.event.client_payload.issue-number != null
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          issue-number: ${{ github.event.client_payload.issue-number }}
          body: |
            Alle autotestene gikk grønt!
            Deployer fpformidling til t4!

      - name: Trigger deploy til t4
        if: github.event.client_payload.success == 'true' && github.event.client_payload.issue-number != null
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          issue-number: ${{ github.event.client_payload.issue-number }}
          body: /promote dev-fss t4

      - name: Test failure
        if: github.event.client_payload.success == 'false' && github.event.client_payload.issue-number != null
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          issue-number: ${{ github.event.client_payload.issue-number }}
          body: |
            Testene kjørt av Github action feilet!
            Resultatet kan være falsk negativt!
            Sammenlign resultatet med Jenkins før eventuell promote!
            Deployer derfor IKKE fpformidling til t4!
